version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - MONGO_INITDB_DATABSE=test-db
      - MONGO_INITDB_ROOT_USERNAME=test-user
      - MONGO_INITDB_ROOT_PASSWORD=test-password
      - APP_EPIRATION_TIME=30
      - APP_PORT_NUM=80
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABSE=test-db
      - MONGO_INITDB_ROOT_USERNAME=test-user
      - MONGO_INITDB_ROOT_PASSWORD=test-password