apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: url-shorner-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-shorner-dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50